spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://203.195.193.58:3306/user-center?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=true
        username: mikeylay
        password: Ssslew128.akang
    # session失效的时间为1天
    session:
        timeout: 86400
